name: Build and Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Generate build tag number
      id: build-tag
      uses: onyxmueller/build-tag-number@v1
      with:
        token: ${{ secrets.PAT_TOKEN }}
        prefix: 'v1.0'  # Example prefix if needed

    - name: Echo build tag number
      run: echo "Build tag number is ${{ steps.build-tag.outputs.tag }}"
